<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ApacheThriftGeneratedLinter' => 'src/ApacheThriftGeneratedLinter.php',
    'ApacheThriftLinter' => 'src/ApacheThriftLinter.php',
    'BlackLinter' => 'src/BlackLinter.php',
    'CheckstyleLinter' => 'src/CheckstyleLinter.php',
    'DetectSecretsLinter' => 'src/DetectSecretsLinter.php',
    'ESLintLinter' => 'src/ESLintLinter.php',
    'Flake8Linter' => 'src/Flake8Linter.php',
    'FlawfinderLinter' => 'src/FlawfinderLinter.php',
    'GoVetLinter' => 'src/GoVetLinter.php',
    'NodeExternalLinter' => 'src/NodeExternalLinter.php',
    'PinterestPylintLinter' => 'src/PinterestPylintLinter.php',
    'PrettierESLintLinter' => 'src/PrettierESLintLinter.php',
    'PrettierLinter' => 'src/PrettierLinter.php',
    'PythonExternalLinter' => 'src/PythonExternalLinter.php',
    'PythonImportsLinter' => 'src/PythonImportsLinter.php',
    'PythonIsortLinter' => 'src/PythonIsortLinter.php',
    'PythonRequirementsLinter' => 'src/PythonRequirementsLinter.php',
  ),
  'function' => array(),
  'xmap' => array(
    'ApacheThriftGeneratedLinter' => 'ArcanistLinter',
    'ApacheThriftLinter' => 'ArcanistExternalLinter',
    'BlackLinter' => 'PythonExternalLinter',
    'CheckstyleLinter' => 'ArcanistExternalLinter',
    'DetectSecretsLinter' => 'PythonExternalLinter',
    'ESLintLinter' => 'NodeExternalLinter',
    'Flake8Linter' => 'PythonExternalLinter',
    'FlawfinderLinter' => 'ArcanistExternalLinter',
    'GoVetLinter' => 'ArcanistExternalLinter',
    'NodeExternalLinter' => 'ArcanistExternalLinter',
    'PinterestPylintLinter' => 'PythonExternalLinter',
    'PrettierESLintLinter' => 'NodeExternalLinter',
    'PrettierLinter' => 'NodeExternalLinter',
    'PythonExternalLinter' => 'ArcanistExternalLinter',
    'PythonImportsLinter' => 'ArcanistLinter',
    'PythonIsortLinter' => 'PythonExternalLinter',
    'PythonRequirementsLinter' => 'ArcanistLinter',
  ),
));
